name: Pak Takis

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Make dummy package lock
      run: echo '{"name":"dummy","version":"1.0.0","lockfileVersion":3,"requires":true,"packages":{}}}' > package-lock.json
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    - run: git clone https://github.com/UnmatchedBracket/PaK3
    - run: bash -c "cd PaK3; npm i"
    - run: node PaK3/main.js src/ TakisBuild-${{ shell date +%d-%m-%Y }}.pk3
    # -$(date '+%d-%m-%Y')
    - name: Upload Takis
      uses: actions/upload-artifact@v3.1.0
      with:
        name: 'takis.zip'
        path: "TakisBuild-${{ shell date +%d-%m-%Y }}.pk3"
        if-no-files-found: error
  discord:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download file
        uses: actions/download-artifact@v2
        with:
          name: 'takis'
      - run: mv takis* TakisBuild-${{ shell date +%d-%m-%Y }}.pk3
      - name: Send to discord channel
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: TakisBuild-${{ shell date +%d-%m-%Y }}.pk3
